# Generated by Django 3.2.9 on 2021-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hist_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_Num1', models.IntegerField()),
                ('stu_Num2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num_from', models.IntegerField()),
                ('stu_num_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.IntegerField()),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('satisfaction', models.IntegerField()),
            ],
        ),
    ]
