# Generated by Django 3.2.9 on 2021-12-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_match',
            name='insert_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hist_match',
            name='stu_Num1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hist_match',
            name='stu_Num2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='satisfaction_point',
            name='stu_num_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='satisfaction_point',
            name='stu_num_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='stu_gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='stu_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='stu_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='satisfaction',
            field=models.IntegerField(null=True),
        ),
    ]
